# Pandas & NumPy Tutorial

## NumPy (Numerical Python) Giriş

NumPy, diziler, çok boyutlu diziler ve matrislerle çalışma imkanı sağlayan bir Python kütüphanesidir. Doğrusal cebir, fourier dönüşümü ve matrisler alanında çalışmak için de gerekli özelleşmiş işlevlere sahiptir. Açık kaynaklı bir projedir ve 2005 yılında Travis Oliphant tarafından oluşturulmuştur.

https://github.com/numpy/numpy

**Neden NumPy?**

*   Python'da dizilerin amacına hizmet eden listelerimiz var, ancak NumPy, geleneksel Python listelerinden 50 kata kadar daha hızlı bir dizi nesnesi sağlamayı amaçlamaktadır.
*   NumPy'deki dizi nesnesi ndarray olarak adlandırılır, ndarray ile çalışmayı çok kolaylaştıran birçok destekleyici işlev sağlar.
*   Diziler, hız ve kaynakların çok önemli olduğu veri biliminde çok sık kullanılır.

**NumPy Neden Listelerden Daha Hızlı?**
NumPy bir Python kütüphanesidir ve kısmen Python’da yazılmıştır, ancak hızlı hesaplama gerektiren parçaların çoğu C veya C ++ ile yazılmıştır.


## Kütüphane Kurulumları
Colab üzerinde aşağıdaki komutu kod hücresine yazarak varsayılan olarak yüklenmemiş kütüphaneleri yükleyebiliriz:

```
! pip install [kütüphane_ismi]
```

https://docs.python.org/tr/3/installing/index.html

NumPy kurulduktan sonra, **import** anahtar sözcüğünü ekleyerek uygulamalarınıza aktarın. **NumPy** genellikle **np** takma adı (alias) altında içe aktarılır. Artık NumPy paketinden numpy yerine np olarak bahsedilebilir.


In [7]:
import numpy as np


Sürüm dizesi __version__ niteliği altında saklanır.

In [3]:
print(np.__version__)
print(pd.__version__)

1.25.2
1.5.3


NumPy dizilerle çalışmak için kullanılır. NumPy'deki dizi nesnesi **ndarray** olarak adlandırılır.

`array() `fonksiyonunu kullanarak bir **NumPy ndarray nesnesi** oluşturabiliriz.

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>



Bir ndarray oluşturmak için, bir listeyi, tuple’ı veya herhangi bir dizi benzeri nesneyi array() yöntemine geçirebiliriz ve bu bir ndarray‘e dönüştürülür:

In [6]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


## Dizilerdeki Boyutlar

*   0-D diziler veya Skalarlar, bir dizideki öğelerdir. Bir dizideki her değer bir 0-D dizisidir.








In [11]:
a = np.array(42)

print(a)

42


*   1-D Diziler, öğeleri 0-D dizileri olan bir dizidir, tek boyutlu veya 1-D dizi olarak adlandırılır. Bunlar en yaygın ve temel dizilerdir.

In [12]:
b = np.array([1, 2, 3, 4, 5])

print(b)

[1 2 3 4 5]


*   2-D Diziler, öğeleri 1 boyutlu dizilerdir,genellikle matris veya 2. derece tensörleri temsil etmek için kullanılır.

In [13]:
c = np.array([[1, 2, 3], [4, 5, 6]])

print(c)

[[1 2 3]
 [4 5 6]]


*   3-D Diziler, öğeleri 2 boyutlu dizilerdir (matrislerdir) ve genellikle 3. dereceden bir tensörü temsil etmek için kullanılır.

In [14]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


NumPy Dizileri, dizinin kaç boyuta sahip olduğunu bize söyleyen bir tamsayı döndüren `ndim` niteliğini sağlar. Dizilerin kaç boyuta sahip olduğunu kontrol etmek için ndim kullanabiliriz:

In [15]:
print(a.ndim)  # 0
print(b.ndim)  # 1
print(c.ndim)  # 2
print(d.ndim)  # 3

0
1
2
3


## NumPy Dizi İndeksleme
Dizi indeksleme, bir dizi öğesine erişimle aynıdır. Bir dizi öğesine, dizin numarasına başvurarak erişebilirsiniz. **NumPy dizilerindeki indexler 0 ile başlar, yani bu, ilk öğenin indexi 0’a ve ikincinin indexi 1’e sahip olduğu anlamına gelir.**



In [17]:
print(b[0])  # 1
print(b[1])  # 1

1
2


2 boyutlu dizilerden öğelere erişmek için, öğenin boyutunu ve dizinini temsil eden virgülle ayrılmış tamsayılar kullanabiliriz.

In [18]:
print('1. boyuttaki 2.eleman: ', c[0, 1])

1. boyuttaki 2.eleman:  2


In [19]:
print(d[0, 1, 2])

6


Bir diziye sondan erişmek için negatif indeksleme kullanabilirsiniz. Örneğin, 2. boyuttan son öğeyi yazdırmak için:

In [20]:
print('2. boyuttaki son eleman: ', c[1, -1])

2. boyuttaki son eleman:  6


Python’da dilimleme, belirli bir dizinden belirli bir dizine öğe almak anlamına gelir.

İndeks yerine dilimi şu şekilde geçiririz: `[start: end]`. Ayrıca adımı şu şekilde tanımlayabiliriz: `[start: end: step]`.

**Not: Sonuç, başlangıç indexini içerir, ancak bitiş indexini hariç tutar.**

Aşağıdaki diziden index 1’den index 5’e öğeleri dilimlemek için:

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])   # [2 3 4 5]

[2 3 4 5]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])   # [5 6 7]

[5 6 7]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])   # [1 2 3 4]

[1 2 3 4]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])   # [5 6]

[5 6]


Dilimleme adımını belirlemek için `step` değerini kullanınız. Örneğin index 1’den index 5’e diğer kadar her 2 ögeden birini döndürür:

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])   # [2 4]

[2 4]


Dizinin tamamındaki her 2. ögeden birini döndürür:

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])   # [1 3 5 7]

[1 3 5 7]


**NumPy Dizi Şekli (Shape)**



> Bir dizinin şekli (shape), her boyuttaki öğelerin sayısıdır.NumPy dizileri, her indexe karşılık gelen öğelerin sayısına sahip bir tuple döndüren shape adlı bir özniteliğe sahiptir. 2 boyutlu bir dizinin şeklini yazdıralım:



In [31]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)  # (2, 4)

(2, 4)


Yukarıdaki örnek (2, 4) değerini döndürür; bu, dizinin 2 boyuta sahip olduğu ve her boyutun 4 öğeye sahip olduğu anlamına gelir.

**NumPy Dizi Yeniden Şekillendirme (Reshaping)**

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Aşağıdaki 1-D diziyi 12 elemanlı bir 3-D dizisine dönüştürelim. En dıştaki boyut, her biri 2 öğe içeren 3 dizi içeren 2 diziye sahip olacaktır:

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Yeniden şekillendirme için gerekli öğeler her iki şekilde de eşit olduğu sürece reshape yapabiliriz.** 8 öğeli bir 1D dizisini 2 satırlı 2D dizide 4 öğeye yeniden şekillendirebiliriz, ancak 3×3 = 9 öğe gerektireceği için onu 3 öğeli 3 satırlı 2D diziye yeniden şekillendiremeyiz.

8 öğeli 1D diziyi, her boyutta 3 öğeli bir 2D diziye dönüştürmeyi deneyelim (bir hataya neden olur):

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 8 into shape (3,3)

**Dizileri Düzleştirme (Flatten)**

> Düzleştirme dizisi, çok boyutlu bir diziyi 1 boyutlu bir diziye dönüştürmek anlamına gelir. Bunu yapmak için reshape(-1) kullanabiliriz.



In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)  # [1 2 3 4 5 6]

[1 2 3 4 5 6]


**NumPy Dizilerini Birleştirme (Join)**

> GBirleştirme (Joining), iki veya daha fazla dizinin içeriğini tek bir diziye koymak anlamına gelir. SQL’de tabloları bir anahtara dayalı olarak birleştiririz, NumPy’de ise dizileri eksenlere göre birleştirebiliriz. Boyutla birlikte concatenate() işlevine birleştirmek istediğimiz bir dizi diziyi iletiriz. Boyut açıkça geçirilmezse 0 olarak alınır.



In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


iki 2 boyutlu diziyi birleştirelim (axis = 1):

In [37]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


# Kaynak : https://www.w3schools.com/python/numpy/default.asp
NumPy hakkında daha ayrıntılı bilgi için yukarıdaki kaynaktan faydalanabilirsiniz.


# Pandas'a Giriş

Pandas, büyük verileri analiz etmemizi ve istatistiksel teorilere dayalı sonuçlar çıkarmamızı sağlayan, veri kümeleriyle çalışmak için kullanılan bir Python kütüphanesidir.

Verileri analiz etmek, temizlemek, keşfetmek ve manipüle etmek için işlevlere sahiptir.

"Pandas" adı hem "Panel Verisi" hem de "Python Veri Analizi" anlamına gelmektedir ve 2008 yılında Wes McKinney tarafından oluşturulmuştur.

 https://github.com/pandas-dev/pandas


In [1]:
import pandas as pd

**Pandas'ta temel veri yapıları**
Pandas, verileri işlemek için iki tür sınıf sağlar:

*   **Series:** herhangi bir türden veri tutan tek boyutlu etiketli bir dizi
tamsayılar, dizeler, Python nesneleri vb. gibi.
*   **DataFrame:** iki boyutlu bir dizi veya satır ve sütunları olan bir tablo gibi verileri tutan iki boyutlu bir veri yapısıdır.




## Series
Pandas Serisi, tablodaki bir sütun gibidir.
Herhangi bir türde veri tutan tek boyutlu bir dizidir.

In [8]:
a = [1, 7, 2]

myvar = pd.Series(a)
s = pd.Series([1, 3, 5, np.nan, 6, 8])

print(myvar)
print(s)

0    1
1    7
2    2
dtype: int64
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


Başka bir şey belirtilmezse, değerler indeks numaralarıyla etiketlenir. İlk değerin indeksi 0, ikinci değerin indeksi 1 vb.

**Etiketler(Labels)** ise  belirtilen bir değere erişmek için kullanılabilir.


In [9]:
a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64


Etiket oluşturduğunuzda, etikete başvurarak bir öğeye erişebilirsiniz.

In [10]:
print(myvar["y"])

7


**Seri Olarak Anahtar/Değer Nesneleri (Key/Value Objects)**

Seri oluştururken sözlük gibi bir anahtar/değer nesnesi de kullanabilirsiniz.
**Sözlüğün anahtarları etiketlere dönüşür.**

In [11]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


Sözlükteki öğelerden yalnızca bazılarını seçmek için, dizin bağımsız değişkenini kullanın ve yalnızca Seriye dahil etmek istediğiniz öğeleri belirtin.

In [12]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64


# DataFrames

Pandas'taki veri kümeleri genellikle DataFrame adı verilen çok boyutlu tablolardır.

Seri bir sütun gibidir, DataFrame ise tablonun tamamıdır.


Bir Python sözlüğünde kalori cetveli tanımlayalım.

In [16]:
KALORI_CETVELI = {"YIYECEK": ['BAL','CEVIZ','NOHUT', 'SUCUK', 'BIFTEK', 'TAVUK'],
                  "MIKTAR": [5,100,5,24,100,100],
                  "KALORI": [15,651,360,108,156,215]}

Sözlüğü Pandas `DataFrame`'ine çevirelim.

In [19]:
KALORI_CETVELI_DF = pd.DataFrame(KALORI_CETVELI)

KALORI_CETVELI_DF

YIYECEK  MIKTAR  KALORI
0     BAL       5      15
1   CEVIZ     100     651
2   NOHUT       5     360
3   SUCUK      24     108
4  BIFTEK     100     156
5   TAVUK     100     215

Yukarıdaki sonuçtan da görebileceğiniz gibi, DataFrame satırları ve sütunları olan bir tablo gibidir.

Pandas, belirtilen bir veya daha fazla satırı döndürmek için loc niteliğini kullanır. Bu örnek bir Pandas Serisi döndürür.
[ ] kullanıldığında, sonuç bir Pandas DataFrame'dir.

In [46]:
print(KALORI_CETVELI_DF.loc[0])

yiyecek    BAL
miktar       5
kalori      15
Name: 0, dtype: object


In [55]:
print(KALORI_CETVELI_DF.iloc[1:4])

  yiyecek  miktar  kalori
1   CEVIZ     100     651
2   NOHUT       5     360
3   SUCUK      24     108


İlk 5 değeri görelim.

In [20]:
KALORI_CETVELI_DF.head()

YIYECEK  MIKTAR  KALORI
0     BAL       5      15
1   CEVIZ     100     651
2   NOHUT       5     360
3   SUCUK      24     108
4  BIFTEK     100     156

İlk 3 değeri görelim.

In [21]:
KALORI_CETVELI_DF.head(3)

YIYECEK  MIKTAR  KALORI
0     BAL       5      15
1   CEVIZ     100     651
2   NOHUT       5     360

Son 3 değeri görelim.

In [22]:
KALORI_CETVELI_DF.tail(3)

YIYECEK  MIKTAR  KALORI
3   SUCUK      24     108
4  BIFTEK     100     156
5   TAVUK     100     215

Aynı zamanda özniteliklerimiz olan sütun adlarını görelim.

In [23]:
KALORI_CETVELI_DF.columns

Index(['YIYECEK', 'MIKTAR', 'KALORI'], dtype='object')

Temel bilgileri görelim.

In [24]:
KALORI_CETVELI_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   YIYECEK  6 non-null      object
 1   MIKTAR   6 non-null      int64 
 2   KALORI   6 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 272.0+ bytes


İstatistiksel bazı bilgileri görelim

In [25]:
KALORI_CETVELI_DF.describe()

MIKTAR      KALORI
count    6.000000    6.000000
mean    55.666667  250.833333
std     49.057789  227.308967
min      5.000000   15.000000
25%      9.750000  120.000000
50%     62.000000  185.500000
75%    100.000000  323.750000
max    100.000000  651.000000

Veri tiplerini görelim.

In [26]:
KALORI_CETVELI_DF.dtypes

YIYECEK    object
MIKTAR      int64
KALORI      int64
dtype: object

`YIYECEK` başlıklı sütunda yer alan değerleri görelim.

In [27]:
KALORI_CETVELI_DF['YIYECEK']

0       BAL
1     CEVIZ
2     NOHUT
3     SUCUK
4    BIFTEK
5     TAVUK
Name: YIYECEK, dtype: object

`YIYECEK` başlıklı sütunda yer alan değerleri bu şekilde de görebiliriz.

In [28]:
KALORI_CETVELI_DF.YIYECEK

0       BAL
1     CEVIZ
2     NOHUT
3     SUCUK
4    BIFTEK
5     TAVUK
Name: YIYECEK, dtype: object

`YIYECEK` ve `KALORI` sütunlarının tüm satırlarını görelim.

In [29]:
KALORI_CETVELI_DF.loc[:,['YIYECEK', 'KALORI']]

YIYECEK  KALORI
0     BAL      15
1   CEVIZ     651
2   NOHUT     360
3   SUCUK     108
4  BIFTEK     156
5   TAVUK     215

`YIYECEK` ve `KALORI` sütunlarının ilk üç satırını görelim.

In [30]:
KALORI_CETVELI_DF.loc[:2,['YIYECEK', 'KALORI']]

YIYECEK  KALORI
0     BAL      15
1   CEVIZ     651
2   NOHUT     360

`KALORI`değeri 200'den fazla olanları görelim

In [31]:
KALORI_CETVELI_DF[KALORI_CETVELI_DF.KALORI>200]

YIYECEK  MIKTAR  KALORI
1   CEVIZ     100     651
2   NOHUT       5     360
5   TAVUK     100     215

`KALORI`si 200'den ve `MIKTAR`ı 50'den fazla olanlar için iki adet filtre oluşturalım.

In [32]:
filtre1 = KALORI_CETVELI_DF.KALORI > 200
filtre2 = KALORI_CETVELI_DF.MIKTAR > 50

Filtreleri uygulayalım.

In [33]:
KALORI_CETVELI_DF[filtre1 & filtre2]

YIYECEK  MIKTAR  KALORI
1   CEVIZ     100     651
5   TAVUK     100     215

Kalori ortalamasını görelim.

In [34]:
KALORI_CETVELI_DF.KALORI.mean()

250.83333333333334

Ortalamayı Numpy'da yer alan `np.mean()` ile de bulabiliriz.

In [35]:
np.mean(KALORI_CETVELI_DF.KALORI)

250.83333333333334

`KALORI_SEVIYESI` adında yeni bir sütun açalım ve yiyeceğin kalorisi 200'den küçük ise `NORMAL` diğer durumlarda `YUKSEK` olacak şeklinde değerler atayalım.

In [36]:
KALORI_CETVELI_DF['KALORI_SEVIYESI'] = ['NORMAL' if kalori < 200 else 'YUKSEK' for kalori in KALORI_CETVELI_DF.KALORI]
KALORI_CETVELI_DF

YIYECEK  MIKTAR  KALORI KALORI_SEVIYESI
0     BAL       5      15          NORMAL
1   CEVIZ     100     651          YUKSEK
2   NOHUT       5     360          YUKSEK
3   SUCUK      24     108          NORMAL
4  BIFTEK     100     156          NORMAL
5   TAVUK     100     215          YUKSEK

Sütun isimlerini **küçük harflerle** değiştirelim.

In [37]:
KALORI_CETVELI_DF.columns = [isim.lower() for isim in KALORI_CETVELI_DF.columns]
KALORI_CETVELI_DF

yiyecek  miktar  kalori kalori_seviyesi
0     BAL       5      15          NORMAL
1   CEVIZ     100     651          YUKSEK
2   NOHUT       5     360          YUKSEK
3   SUCUK      24     108          NORMAL
4  BIFTEK     100     156          NORMAL
5   TAVUK     100     215          YUKSEK

`kalori_seviyesi` sütununu **silelim**.

In [38]:
KALORI_CETVELI_DF.drop(['kalori_seviyesi'], axis = 1, inplace = True)
KALORI_CETVELI_DF

yiyecek  miktar  kalori
0     BAL       5      15
1   CEVIZ     100     651
2   NOHUT       5     360
3   SUCUK      24     108
4  BIFTEK     100     156
5   TAVUK     100     215

`KALORI_CETVELI_DF` ile `KALORI_CETVELI_DF` alt alta birleştirelim.

In [39]:
cift = pd.concat([KALORI_CETVELI_DF,KALORI_CETVELI_DF], axis = 0)
cift

yiyecek  miktar  kalori
0     BAL       5      15
1   CEVIZ     100     651
2   NOHUT       5     360
3   SUCUK      24     108
4  BIFTEK     100     156
5   TAVUK     100     215
0     BAL       5      15
1   CEVIZ     100     651
2   NOHUT       5     360
3   SUCUK      24     108
4  BIFTEK     100     156
5   TAVUK     100     215

index değerlerini sıfırlamak için `reset_index()` kullanabiliriz.

In [40]:
cift.reset_index(drop = True, inplace = True)
cift

yiyecek  miktar  kalori
0      BAL       5      15
1    CEVIZ     100     651
2    NOHUT       5     360
3    SUCUK      24     108
4   BIFTEK     100     156
5    TAVUK     100     215
6      BAL       5      15
7    CEVIZ     100     651
8    NOHUT       5     360
9    SUCUK      24     108
10  BIFTEK     100     156
11   TAVUK     100     215

Miktar birimimiz gram idi. Bunu kilograma çevirelim.

In [41]:
cift["miktar"] = [miktar / 1000 for miktar in cift.miktar]
cift

yiyecek  miktar  kalori
0      BAL   0.005      15
1    CEVIZ   0.100     651
2    NOHUT   0.005     360
3    SUCUK   0.024     108
4   BIFTEK   0.100     156
5    TAVUK   0.100     215
6      BAL   0.005      15
7    CEVIZ   0.100     651
8    NOHUT   0.005     360
9    SUCUK   0.024     108
10  BIFTEK   0.100     156
11   TAVUK   0.100     215

Gramdan kilograma çeviren bir fonksiyon tanımlayalım

In [42]:
def kg2gr(x):
    return x * 1000

Miktar sütununa bu fonksiyonu uygulayarak tekrar miktarın birimini gram olarak değiştirelim.

In [43]:
cift.miktar = cift.miktar.apply(kg2gr)
cift

yiyecek  miktar  kalori
0      BAL     5.0      15
1    CEVIZ   100.0     651
2    NOHUT     5.0     360
3    SUCUK    24.0     108
4   BIFTEK   100.0     156
5    TAVUK   100.0     215
6      BAL     5.0      15
7    CEVIZ   100.0     651
8    NOHUT     5.0     360
9    SUCUK    24.0     108
10  BIFTEK   100.0     156
11   TAVUK   100.0     215

In [56]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [58]:
df=pd.read_csv('gdrive/My Drive/Iris.csv')

In [59]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]